### ISSUE TITLE
while (ElementActions.isElementDisplayed(driver,element Locator)) Expected to return true or false, but it throw exception that zero item is found. 

### ISSUE THREAD

**Issue by amirmagdy304** [MohabMohie/using_SHAFT_ENGINE#32]
while i am upgrading to shaft engine i faced below case. 
i made this code in order to check if error message is displayed then press discard button.   
          while (ElementActions.isElementDisplayed(driver,Discard)) {
                click(Discard);
                Thread.sleep(100);
            }
but it always consider the test case as failed with message "zero elements found matching this locator "By.xpath:"

while if i used this code it work normally. 

           while (driver.findElement(Discard).isDisplayed()) {
                click(Discard);
            
[Logs 2021-10-27.txt](https://github.com/MohabMohie/using_SHAFT_ENGINE/files/7424368/Logs.2021-10-27.txt)
}

**Comment by amirmagdy304** [comment]
The Element doesn't exist, and I know that. 
the idea here that I need to check if the element is displayed, then do a specific action, else the automation will do another behavior. 
So I used the "while" which expects a boolean result.And as per the Shaft documentation "ElementActions.isElementDisplayed" is a boolean however instead of returning a False in case the element didn't exist, it returns the error message.  

I hope that I could deliver the problem to you correctly and clearly.

**Comment by MohabMohie** [comment]
This method checks if the element is displayed (given that it exists) in which case it returns true, if it is not displayed (given that it exists) it returns false.

There is another method that returns an int (element count) you can use it to do the check that you need.

PS: it is against best practices to develop this kind of loops/conditions as a test case is defined as a static set of steps that lead to a dynamic expected result and compares it against a static expected result.

**Comment by amirmagdy304** [comment]
I totally agree with you, that this is not the best practices, but I have a special case where the system page loading and login take too much time.So I have to load the page and login one time in order to save the testing time. 
and in order to be sure that all test cases to be run, I made a special method to be called @aftermethod to clean the page for the next test case by closing any Error message which may appear on the previous one.

I will try the element count. Thanks for your support.
